# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: ci-python-unittest

on:
  workflow_run:
    workflows: ["Update requirements.txt [bot]"]
    branches:
      - "**"
      - "!master"
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./request_handler/requirements.txt
      - name: Test with unittest
        run: |
          python scripts/test.py'